name: dev-release

on:
  workflow_dispatch:

jobs:
  build:
    name: Weekly Release Notation Binaries
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [1.18]
      fail-fast: true
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add version tag
        run: export TAG_VERSION=`cat ./internal/version/version.go | grep "Version = " | awk -F '"' '{print $2}'`.dev.`date +%Y%m%d%H%M%S`
        run: git tag -f $TAG_VERSION && git push origin $TAG_VERSION
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
